name: Build v86 and Deploy EdgeOne

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout v86
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            make \
            clang \
            python3 \
            nasm

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Build v86
        run: |
          make all

      - name: Check output
        run: |
          ls -lah

      - name: Install EdgeOne CLI
        run: |
          npm install -g edgeone

      - name: Deploy to EdgeOne
        run: |
          edgeone makers deploy . \
          -n YOUR_PROJECT_NAME \
          -t ${{ secrets.EDGEONE_TOKEN }}
